project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: " "
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: why_slang.qmd
        text: "Why SlAnG?"
      - href: lab.qmd
        text: "Lab"
      - href: people.qmd
        text: "People"
      - href: projects.qmd
        text: "Projects"
      - href: contact.qmd
        text: "Contact"
      - href: news.qmd
        text: "News"
  search: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source
