---
title: "Why SlAnG?"
toc: false
page-layout: full
about: 
  template: jolla
editor: 
  mode: source
---

<div style="text-align: justify;">

Aside from being an intriguing acronym for our longer name, the **S**ocio**l**inguistic **An**alysis **G**roup, *slang* is a word that resonates both in everyday language and in the field of sociolinguistics. When people hear the word *slang*, they often associate it with language forms that are ‘incorrect’, ‘informal’, or improper – something associated with youth that falls outside of the umbrella of ‘good’ language. We reject this idea. In our lab, we are committed to the analysis of all kinds of language forms, regardless of their level of social acceptability. We are committed to analyzing how all kinds of language, formal and informal, standard and non-standard, are used, understood, and evaluated in society, and what variable language patterns reveal about language itself.

Some have dismissed this kind of research as mere ‘butterfly-collecting’. This metaphor suggests that sociolinguists are merely cataloging surface-level variations in language, that, while interesting, are not especially relevant to revealing anything interesting about linguistic structure. However, our work demonstrates variation is not random; it reflects structured patterns shaped by linguistic, social, and cognitive factors. Rather than being external quirks or deviations, these "butterflies" – phonetic, morphosyntactic, lexical, pragmatic, or semantic differences and innovations – are essential components of how language functions and evolves.

By embracing this perspective, we challenge outdated notions of linguistic correctness and instead highlight the systematic nature of language variation. Just as every butterfly provides insight into the larger ecosystem, every instance of linguistic variation—whether it be slang, formal speech, dialect changes, or codeswitching – offers a window into the very nature of language.

</div>

